language: go
go:
  - "1.13.x"

script:
  - make build test

before_deploy:
  - make binaries
  - sha256sum cvscan-*.tar.gz > checksums.sha256
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install multipart-post -v 2.2.0

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file:
      - checksums.sha256
      - cvscan-*.tar.gz
    skip_cleanup: true
    on:
      tags: true
